#!/bin/sh
# Author: Stefan Kuhn <woudan@hispeed.ch>
#
# toggles cpu governors
# (or loops through the list if more then 2 governors are available)

# sanity check
if [ ! -x /usr/bin/cpufreq-info ]  || [ ! -x /usr/bin/cpufreq-set ]; then
	echo "/usr/bin/cpufreq-info or /usr/bin/cpufreq-set not found"
	echo "Do you have sys-power/cpufreqd installed?"
	exit 1
fi


setNextGovernor()
{
	# get available governors
	local allGovernors=$(cpufreq-info -g)
	local currentGov=$(cpufreq-info -p | sed -r 's/^.*[[:space:]]+([[:alnum:]]+)$/\1/')
	local found=0
	local newGov=
	for gov in $allGovernors; do
		if [ $found -ne 0 ]; then
			newGov=$gov
			break
		fi
		[ "$gov" == "$currentGov" ] && found=1
	done
	# last gov was active, set to first
	if [ "$newGov" == '' ]; then
		newGov=$(echo "$allGovernors" | sed -r 's/^([[:alnum:]]+)[[:space:]]+.*$/\1/')
	fi
	cpufreq-set -r -g $newGov
	echo "Old governor was \"$currentGov\", new is \"$newGov\"."
	echo "Available governors: \"$allGovernors\""
	exit 0
}

setNextGovernor
